services:
  - type: web
    name: nsl-kdd-processor
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      python manage.py migrate
      gunicorn nsl_kdd_processor.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nsl_kdd_processor.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18